### ISSUE TITLE
Are we need Nvidia to run this code?

### ISSUE THREAD

**Issue by ahmedAlmasri** [a-jahani/Real-time-Video-Mosaic#1]
I'm trying to run the code on my own machine but I get the error while trying to compile

```
OpenCV Error: No GPU support (The library is compiled without CUDA support) in mallocPitch, file /tmp/opencv@2-20191004-38911-1selm3v/opencv-2.4.13.7/modules/dynamicuda/include/opencv2/dynamicuda/dynamicuda.hpp, line 126
```

I want to know if I need Nvidia to run the code, My device is Mac book pro 2018

**Comment by jahaniam** [comment]
For cuda yes, you need a gpu with cuda support.  you can also run it on cpu which is so slower

**Comment by ahmedAlmasri** [comment]
How to build your project in cpu do you have a example ? 

Thank you

**Comment by jahaniam** [comment]
Just use prebuild opencv. You don't need to compile opencv from source. If you want to do it, you can turn off the cuda support.

**Comment by mnayef95** [comment]
@a-jahani But with CUDA support off we can't run the project, so we need to rewrite the project from scratch using CPU not GPU?

**Comment by jahaniam** [comment]
You are right. You need a GPU to do warping section. You can use cuda for SURF feature extraction as well. It's been a while I haven't read the code! I might rewrite this code in python if I see attention.

**Comment by heng2j** [comment]
Hi @a-jahani, yes it will be great if there is a python version. Your work is very promising to a problem that I am trying to solve for my own project.

**Comment by sharoseali** [comment]
HI, @jahaniam  and  @heng2j  did anyone of you work for python version. ??

**Comment by jahaniam** [comment]
@sharoseali @ahmedAlmasri  @heng2j  FYI if you are still interested, because of lots of requests, I finally wrote an experimental python version. You don't need cuda for that. It lacks a few sanity checks for robustness but it should be ok and easy to apply on your own.
